### ISSUE TITLE
Aaltoverb algorithm license and usage

### ISSUE THREAD

**Issue by colugomusic** [madronalabs/madronalib#24]
I'm working on a DAW which has a number of built-in effects. I added a reverb based on the example algorithm from reverb.cpp and it works beautifully. I assume this is still MIT licensed along with the rest of the library though as I understand it this algorithm is the basis for your Aaltoverb plugin so I just wanted to double check with you that there is no licensing issue with me using it in my project.

**Comment by madronalabs** [comment]
Yes that's fine. Thanks for asking. I look forward to seeing how your project develops!

**Comment by norton-corbett** [comment]
Brilliant thank you!

**Comment by colugomusic** [comment]
Thank you!
