### ISSUE TITLE
grep: /wrkdirs/usr/ports/audio/madronalib/work/madronalib-1.6-1016-g103895f/build/bin/Release/ReverbExample.app/Contents/Info.plist: No such file or directory

### ISSUE THREAD

**Issue by yurivict** [madronalabs/madronalib#38]

**Comment by madronalabs** [comment]
Can you tell me what you were trying to do when you got this error? And on what OS?

**Comment by yurivict** [comment]
I was building it on FreeBSD 12.2

The build succeeds but this error message is printed in the middle.

**Comment by madronalabs** [comment]
fixed by https://github.com/madronalabs/madronalib/commit/8e1f159484fbb29035d8aa417460244b246eafa9
