### ISSUE TITLE
PhasorGen invokes undefined behavior

### ISSUE THREAD

**Issue by colugomusic** [madronalabs/madronalib#50]
PhasorGen works by deliberately overflowing a 32-bit signed integer and then scaling the result back down to a value from 0-1. Signed integer overflow is undefined behavior in C++. However, unsigned overflow is well-defined to wrap around as expected, so this could be rewritten using a uint32 instead (and the offset would also no longer be required.)

**Comment by madronalabs** [comment]
I did not know that this was UB! Did it actually fail on some hardware? Regardless, I will fix it. Thanks for the report.

**Comment by colugomusic** [comment]
No I just spotted it while working on something, I haven't seen it actually cause any real-world issues (as far as I know, I suppose it can be hard to tell with UB)
